### PR TITLE
V3 mrcnpdlk

### PR DESCRIPTION
**Pull request by mrcnpdlk**
- Argument unpacking is available in PHP 5.6 [see here](https://github.com/skipperbent/pecee-pixie/blob/v3-release/src/Pecee/Pixie/QueryBuilder/Adapters/BaseAdapter.php#L485)
  - little fixes in phpDoc

### CODE REVIEW

**Comment by skipperbent** [comment]
Awesome - cool that you know what version things were added. 👍

**Comment by mrcnpdlk** [comment]
PHPStorm helps inspecting the code :)

**Comment by skipperbent** [comment]
@mrcnpdlk Aahh great that's why my PhpStorm didn't complain about the argument unpacking. It was set to PHP 7, I always forget to set it to match the project I'm working on 😆

**Comment by mrcnpdlk** [comment]
You should not only set PHP version in project settings (Settings->Langs->PHP) but also configure composer option with 'sync IDE with composer' flag.

**Pull request merged**
