### PR TITLE
V3 mrcnpdlk

### PR DESCRIPTION
**Pull request by mrcnpdlk**
- Bad usage of join function
  - The special ::class constant are available for PHP >=5.5.0 (composer.json require tag)

### CODE REVIEW

**Comment by skipperbent** [comment]
Hi @mrcnpdlk 

Great work on catching those errors. I was actually just about to deploy a new release with a bunch of improvements, so your changes will be release shortly.

/ Simon

**Comment by mrcnpdlk** [comment]
Hi,
Do you think about  upgrading project to PHP7 syntax?

**Comment by skipperbent** [comment]
@mrcnpdlk 

Yes sir - I just wanted to cleanup the project first, which I've done in version 3.4.0. 

I'm thinking about create a new version which is PHP 7 only and then maintain both versions. What do you think?

/ Simon

**Comment by mrcnpdlk** [comment]
Great idea!
I write only in PHP7, so I can help you refactoring the code as far as possible.

**Comment by skipperbent** [comment]
@mrcnpdlk 

Cool - I've created a `v4-development` and a `v4-release` branch which will contain the next version of Pixie for PHP 7.0. If you're up for the job, you are more than welcome to help with the refactoring - it's always nice with some assistance 😄 

Have a good weekend.

/ Simon

**Pull request merged**
