### PR TITLE
New features, small bugfixes and upgraded dev dependencies

### PR DESCRIPTION
**Pull request by dev-rfc**
Hi, I made a few changes I needed in a project, feel free to merge with your repository if you want to.

You can check the commits for more details about what have changed, but in short it was just a few new methods, small fixes and upgraded dev dependencies for using them on php 8.

All tests are running and passing on php 8.

### CODE REVIEW

**Comment by dqos** [comment]
@skipperbent is this project still maintained? You might want to merge a PR like this 😄

**Comment by dqos** [comment]
@skipperbent

**Comment by dev-rfc** [comment]
I needed to remove the pull request because I changed the branch to "master", and since then I ended changing a bit of more things I needed. I can send it again if you want though.

**Comment by dqos** [comment]
> I needed to remove the pull request because I changed the branch to "master", and since then I ended changing a bit of more things I needed. I can send it again if you want though.

Maybe create a hard-fork of this and proceed developing in a new repo?

**Comment by dqos** [comment]
@skipperbent can we maintain this project? @dev-rfc please do another PR with your latest work.

**Pull request closed without merging**
