### PR TITLE
V4 mrcnpdlk transaction

### PR DESCRIPTION
**Pull request by mrcnpdlk**
**Changes**
  - better support for transaction
  - transaction error throw Exception
  - remove TransactionHaltException class

**Explanation**

For nested transactions unforeseen effects may be appeared.
In my opinion we have to check, if we are in transaction yet/still or not.

Be so kind and look at my commits.

For example, I wrote very simple pseudo-code for tests:

```php
$oQuery->transaction(function (\Pecee\Pixie\QueryBuilder\Transaction $qb) {
    firstTrans($qb);
    secondTrans($qb);
});


/**
 * @param \Pecee\Pixie\QueryBuilder\QueryBuilderHandler $oQuery
 */
function firstTrans(\Pecee\Pixie\QueryBuilder\QueryBuilderHandler $oQuery)
{
    $oQuery->transaction(function (\Pecee\Pixie\QueryBuilder\Transaction $qb) {
        $qb->table('table_one')->insert(['name' => 'foo']);
    });
}

/**
 * @param \Pecee\Pixie\QueryBuilder\QueryBuilderHandler $oQuery
 */
function secondTrans(\Pecee\Pixie\QueryBuilder\QueryBuilderHandler $oQuery)
{
    $oQuery->transaction(function (\Pecee\Pixie\QueryBuilder\Transaction $qb) {
        $qb->table('table_two')->insert(['name' => 'foo']);
    });
}
```

Something like this will generate Exception (function secondTrans throw Exception - column 'name' doesn't exist at table_two):
```
PHP Fatal error:  Uncaught PDOException: There is no active transaction in C:\Users\Marcin\git\pecee-pixie\src\Pecee\Pixie\QueryBuilder\QueryBuilderHandler.php:1221
```

After my changes everything seems to be OK.

Also I decided, that error during transaction have to throw exception up - now only $this is returned. In my opinion application/user should to know, if error happened.

### CODE REVIEW

**Comment by skipperbent** [comment]
Wow, looks really good - you've done a lot of work, great!

Do you want me to create a v4 release?

**Comment by mrcnpdlk** [comment]
Yes,  I do.
I see, You have created v4 - thanks a lot.
Pixie is main library in my project, so I am glad for your fast feedback.

**Comment by skipperbent** [comment]
Me too, I'm also using this many projects and was actually using the original version, but the author just didn't care about fixing any issues which were annoying when you need a bug fixed ASAP on a site running live. 

I added some fixes to the v4-development branch, so you might have to sync your local repository. There is still lots of php 7 optimisations to be done, but now we at least have a version available.

**Comment by mrcnpdlk** [comment]
For the same reasons I am using your project.
Thanks a lot for cooperation.

**Pull request merged**
